import AuroraBackground from "./Components/LandingPage/BgColor";
import SmoothScroll from "./Components/SmoothScroll";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <SmoothScroll>
          <body className="min-h-full  bg-[#f2e8cf]/70  overflow-x-hidden">
            {children}
          </body>
        </SmoothScroll>
      </html>
    </>
  );
}
